name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      specifier:
        description: 'Version to release'
        required: true
        default: 'prerelease'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # needed to push changelog and tag
      id-token: write # needed for provenance data generation
      pages: write # needed to deploy docs site

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.DEPLOY_APP_ID }}
          private-key: ${{ secrets.DEPLOY_PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Setup Git User
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Build and release
        run: node ./node_modules/.bin/nx release --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy
        run: |
          GIT_USER='github-actions[bot]' npx nx deploy docs-site
        env:
          GIT_USER: github-actions[bot]
          GIT_EMAIL: github-actions[bot]@users.noreply.github.com
        if: github.ref == 'refs/heads/main'
